- id: smellcheck
  name: smellcheck
  description: 'Python code smell detector (56 AST checks, 82 refactoring patterns)'
  entry: smellcheck
  language: python
  types: [python]
  require_serial: false
