name: 'smellcheck'
description: 'Python code smell detector -- 56 AST checks, 83 refactoring patterns'
branding:
  icon: 'search'
  color: 'yellow'

inputs:
  paths:
    description: 'Space-separated paths to scan'
    required: false
    default: '.'
  fail-on:
    description: 'Exit 1 on findings at or above this severity: info | warning | error'
    required: false
    default: 'error'
  min-severity:
    description: 'Only display findings at or above this severity: info | warning | error'
    required: false
    default: 'info'
  format:
    description: 'Output format: text | json | github | sarif'
    required: false
    default: 'github'
  diff:
    description: 'Only scan files changed since this git ref (e.g. origin/main, HEAD~1)'
    required: false
    default: ''
  baseline:
    description: 'Path to baseline JSON file (suppress known findings)'
    required: false
    default: ''
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.12'

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install smellcheck
      shell: bash
      run: pip install "$GITHUB_ACTION_PATH"
    - name: Run smellcheck
      shell: bash
      env:
        INPUT_PATHS: ${{ inputs.paths }}
        INPUT_FORMAT: ${{ inputs.format }}
        INPUT_FAIL_ON: ${{ inputs.fail-on }}
        INPUT_MIN_SEV: ${{ inputs.min-severity }}
        INPUT_DIFF: ${{ inputs.diff }}
        INPUT_BASELINE: ${{ inputs.baseline }}
      run: |
        smellcheck $INPUT_PATHS \
          --format "$INPUT_FORMAT" \
          --fail-on "$INPUT_FAIL_ON" \
          --min-severity "$INPUT_MIN_SEV" \
          ${INPUT_DIFF:+--diff "$INPUT_DIFF"} \
          ${INPUT_BASELINE:+--baseline "$INPUT_BASELINE"}
